spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/grow-example-spring-boot-db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 10
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    jms:
      # 如果是true,则是Topic；如果是false或者默认，则是queue。
      pub-sub-domain: false
    pool:
      #连接池启动  默认false
      enabled: false
      # 最大连接数 默认1
      max-connections: 1

rocketmq:
  consumer:
    group: ${spring.application.name}
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: ${spring.application.name}
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false