spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  cloud:
    nacos:
      config:
        file-extension: yml
        group: ${spring.profiles.active}